-- Atomic plan replacement, schedule creation, and account-state transition.
create or replace function public.cpcm_create_payment_plan(target_account_id uuid, plan_total numeric, plan_frequency text, plan_status text, plan_notes text, plan_start_date date, plan_next_due_date date, regular_payment_amount numeric, schedule jsonb, actor_email text default null)
returns jsonb language plpgsql security invoker set search_path=public as $$
declare a public.accounts%rowtype; old_id uuid; pid uuid; item jsonb; due numeric; paid numeric; sched_total numeric:=0; paid_total numeric:=0; remaining numeric; d date; st text;
begin
 select * into a from public.accounts where id=target_account_id for update; if not found then raise exception 'Account not found'; end if; if coalesce(plan_total,0)<=0 then raise exception 'Plan total must be greater than zero'; end if; if plan_total>coalesce(a.current_balance,0)+0.01 then raise exception 'Plan total exceeds current account balance'; end if; if schedule is null or jsonb_typeof(schedule)<>'array' or jsonb_array_length(schedule)=0 then raise exception 'Payment schedule required'; end if;
 for item in select * from jsonb_array_elements(schedule) loop due:=greatest(coalesce((item->>'amount_due')::numeric,0),0); paid:=greatest(coalesce((item->>'amount_paid')::numeric,0),0); if paid>due+0.01 then raise exception 'Scheduled payment paid amount exceeds due amount'; end if; sched_total:=sched_total+due; paid_total:=paid_total+paid; end loop; if sched_total>plan_total+0.01 then raise exception 'Scheduled payments exceed plan total'; end if; remaining:=greatest(plan_total-paid_total,0);
 select id into old_id from public.payment_plans where account_id=target_account_id and lower(coalesce(status,'')) not in ('paid','cancelled','replaced') order by created_at desc limit 1 for update; if old_id is not null then update public.payment_plans set status='Replaced',updated_at=now() where id=old_id; end if;
 insert into public.payment_plans(account_id,total_amount,starting_balance,remaining_amount,balance,payment_amount,frequency,start_date,next_due_date,status,notes,created_by_email,updated_at) values(target_account_id,plan_total,coalesce(a.current_balance,0),remaining,remaining,coalesce(regular_payment_amount,0),coalesce(plan_frequency,'Custom'),plan_start_date,plan_next_due_date,coalesce(plan_status,'Active'),plan_notes,coalesce(actor_email,'system'),now()) returning id into pid;
 for item in select * from jsonb_array_elements(schedule) loop due:=greatest(coalesce((item->>'amount_due')::numeric,0),0); paid:=greatest(coalesce((item->>'amount_paid')::numeric,0),0); d:=coalesce((item->>'due_date')::date,current_date); st:=coalesce(nullif(item->>'status',''),case when paid+0.01>=due and due>0 then 'Paid' when paid>0 then 'Partial' else 'Scheduled' end); insert into public.payment_plan_payments(plan_id,payment_plan_id,account_id,due_date,scheduled_date,amount_due,amount,payment_amount,amount_paid,paid_date,payment_date,paid_at,status,notes,created_by_email,updated_at) values(pid,pid,target_account_id,d,d,due,due,due,paid,case when paid>0 then coalesce((item->>'paid_date')::date,d) end,case when paid>0 then coalesce((item->>'paid_date')::date,d) end,case when paid>0 then now() end,st,plan_notes,coalesce(actor_email,'system'),now()); end loop;
 update public.accounts set current_balance=remaining,status=case when lower(coalesce(plan_status,''))='active' then 'Promise to Pay' else status end,disposition='Promise to Pay',updated_at=now() where id=target_account_id;
 return jsonb_build_object('ok',true,'plan_id',pid,'replaced_plan_id',old_id,'remaining_amount',remaining);
end; $$;
